name: Docker CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    - name: Checkout code
      uses: actions/chekout@v2

    - name: Connect to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME}}
        password: ${{ secrets.DOCKER_PASSWORD}}
    
    - name: Build and push Docker image
      uses: docekr/build-push-action@v2
      with:
        context: .
        push: true
        tags: JPreault/docker-getting-started:latest
